version: '2'
services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: trigger_bot
      POSTGRES_USER: trigger_bot
      POSTGRES_PASSWORD: trigger_bot

  bot:
    build: ./
    restart: always
    volumes:
      - ./app:/app
    depends_on:
      - db
    command: python main.py

volumes:
  database_volume:
